service: dynamodb-batch-samples
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-central-1

custom:
  base: ${self:service}-${sls:stage}

resources:
  Resources:
    batchTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - KeyType: HASH
            AttributeName: UserId
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.base}-table